title: Harshin Kamal Asok
logo: /assets/img/logo.jpg
description: [Google Scolar](https://scholar.google.co.in/citations?user=7whIM1QAAAAJ&hl=en)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
